version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./server/src/main:/app/
    links:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./server/src/main:/app/
  mail:
    image: com.github.korbecki/auth.service:0.0.1-SNAPSHOT
    depends_on:
      db:
        condition: service_healthy
    environment:
      - "SERVER_PORT=9090"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://pg_container:5432/flashcards"
      - "SPRING_DATASOURCE_USERNAME=root"
      - "SPRING_DATASOURCE_PASSWORD=root"
  db:
    container_name: pg_container
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U flashcards" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: flashcards
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
